# Generated by Django 4.2.5 on 2023-09-20 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Product price check date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('link', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='product.product')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_of_products', to='store.store')),
            ],
            options={
                'unique_together': {('product', 'date', 'store')},
            },
        ),
    ]
