# Generated by Django 4.2.5 on 2023-09-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('priority', models.CharField(choices=[('indispensable', 'Indispensable'), ('important', 'Important'), ('nice to have', 'Nice To Have')], default='nice to have')),
                ('key', models.SlugField(verbose_name='Key to compare with similar products')),
                ('categories', models.ManyToManyField(related_name='products', to='category.category')),
            ],
        ),
    ]
